### ISSUE TITLE
gagal di function predictWithEmbeddedModel()

### ISSUE THREAD

**Issue by irsalshabirin** [yusufsyaifudin/indonesia-ner#2]
ini string yang saya masukkan mas :
"REPUBLIKA.CO.ID, JAKARTA BNI Syariah menargetkan pertumbuhan dari tabungan perencanaan syariah (tapenas) menjadi sumber pendanaan jangka panjang. Pertumbuhan pendanaan atau Dana Pihak Ketiga (DPK) BNI Syariah pada 2012 ini ditarget melonjak 30 persen. Produk tapenas, menurut Direktur Kepatuhan BNI Syariah, Imam Teguh Saptono, merupakan tabungan yang membuat nasabah tertib menabung. Pasalnya, tabungan tersebut hanya bisa diambil dalam jangka waktu tertentu. "Produk ini merupakan alternatif antara tabungan biasa dan deposito," ujar dia. Bagi bank, tapenas tersebut dapat menjadi sumber pendanaan untuk periode jangka panjang. Karena bersifat jangka panjang, BNI Syariah pun menawarkan margin tabungan yang lebih tinggi dibandingkan margin tabungan biasa. Nasabah dapat margin yang lebih tinggi tapi lebih fleksibel (waktu penarikannya) dibandingkan deposito," ungkapnya. Menurut Imam, tapenas dapat digunakan untuk berbagai perencanaan. Salah satu yang ditawarkan BNI Syariah adalah tabungan perencanaan untuk pendidikan. Kalau untuk pendidikan, masa penarikannya mengikuti siklus sekolah anak. Ini memaksa untuk tertib menabung," ujarnya. Selain pendidikan, tabungan perencanaan BNI Syariah juga dapat disalurkan ke asuransi. Produk pendanaan tersebut akan mendukung penyaluran pembiayaan BNI Syariah. Untuk pembiayaan, BNI Syariah memiliki kartu pembiayaan Hasanah yang dapat digunakan untuk membiayai pendidikan kursus bahasa Inggris melalui program homestay. Program homestay tersebut mengirimkan anak-anak untuk tinggal sementara di negara Eropa atau Australia untuk belajar bahasa Inggris."

> log4j:WARN No appenders could be found for logger (yusufs.nlp.tokenizerid.Tokenizer).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> Exception in thread "main" java.lang.NoClassDefFoundError: yusufs/generator/randstring/RandomStringGenerator$Mode
> 	at yusufs.nlp.tokenizerid.Tokenizer.addSpaceAfterDot(Tokenizer.java:167)
> 	at yusufs.nlp.tokenizerid.Tokenizer.replaceBoundary(Tokenizer.java:202)
> 	at yusufs.nlp.tokenizerid.Tokenizer.extractSentence(Tokenizer.java:61)
> 	at yusufs.nlp.nerid.Prediction.predict(Prediction.java:41)
> 	at yusufs.nlp.nerid.IndonesiaNER.predictWithEmbeddedModel(IndonesiaNER.java:57)
> 	at co.dust.named.entity.recognition.MainClass.main(MainClass.java:29)
> Caused by: java.lang.ClassNotFoundException: yusufs.generator.randstring.RandomStringGenerator$Mode
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 6 more

bagaimana mas, solusinya ?
apa saya pisah per kalimat ya mas ?

**Comment by irsalshabirin** [comment]
baru paham, yang diinputkan senteces / kalimat, bukan paragraf, jadi harus dipisah2 terlebih dahulu, baru di masukkan ke predict...()

terima kasih 👍
