### ISSUE TITLE
Sekiranya alasan errornya apa ya?

### ISSUE THREAD

**Issue by irfangerard44** [yusufsyaifudin/indonesia-ner#5]
Exception in thread "main" java.lang.NoClassDefFoundError: NLP_ITB/POSTagger/HMM/Decoder/MainTagger
	at yusufs.nlp.nerid.utils.POSTagger.<init>(POSTagger.java:43)
	at yusufs.nlp.nerid.utils.TextSequence.<clinit>(TextSequence.java:26)
	at yusufs.nlp.nerid.Prediction.predict(Prediction.java:35)
	at yusufs.nlp.nerid.IndonesiaNER.predictWithEmbeddedModel(IndonesiaNER.java:57)
	at com.ebdesk.ner.ner.main(ner.java:11)
Caused by: java.lang.ClassNotFoundException: NLP_ITB.POSTagger.HMM.Decoder.MainTagger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

**Comment by hyperstand** [comment]
https://github.com/yusufsyaifudin/ipostagger/blob/master/NLP_ITB/POSTagger/HMM/1.0.0/HMM-1.0.0.jar
